from pathlib import Path


def build_deploy_command(
    script_path: Path,
    remote_user: str,
    remote_host: str,
    local_dataset_dir: Path,
    local_train_script: Path,
    local_output_dir: Path,
    local_requirements: Path,
    remote_venv_activate: str,
    epochs: int,
    batch_size: int,
    window_size: int,
    stride: int,
) -> list[str]:
    return [
        "powershell",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(script_path),
        "-RemoteUser",
        remote_user,
        "-RemoteHost",
        remote_host,
        "-LocalDatasetDir",
        str(local_dataset_dir),
        "-LocalTrainScript",
        str(local_train_script),
        "-LocalOutputDir",
        str(local_output_dir),
        "-LocalRequirements",
        str(local_requirements),
        "-RemoteVenvActivate",
        remote_venv_activate,
        "-Epochs",
        str(epochs),
        "-BatchSize",
        str(batch_size),
        "-WindowSize",
        str(window_size),
        "-Stride",
        str(stride),
    ]
